# @generated by stackless bind. DO NOT EDIT.
# fingerprint: sha256:10a25dc67e384236e9bc6c864ad2fdf4ea0ff7e98afc266fc4d9f9f7293a1b54

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Mapping

IDL_FINGERPRINT = "sha256:10a25dc67e384236e9bc6c864ad2fdf4ea0ff7e98afc266fc4d9f9f7293a1b54"
STACK_NAME = "endpoint-test"
SERVICE_DNS = ("web",)
INTEGRATION_DNS = ()
SECRETS_REQUIRED = ()

@dataclass(frozen=True)
class Integrations:
    pass

class BindError(Exception):
    def __init__(
        self,
        reason: Literal["endpoint", "service", "integration", "output"],
        dns: str,
        output_key: str | None = None,
    ) -> None:
        self.reason = reason
        self.dns = dns
        self.output_key = output_key
        if reason == "service":
            message = f"missing origin for service {dns}"
        elif reason == "endpoint":
            message = f"missing URL for endpoint {dns}"
        elif reason == "integration":
            message = f"missing integration {dns}"
        else:
            message = f"missing output {output_key} for integration {dns}"
        super().__init__(message)

@dataclass(frozen=True)
class Origins:
    web: str

def bind_origins(values: Mapping[str, str]) -> Origins:
    if "web" not in values:
        raise BindError("service", "web")
    return Origins(
        web=values["web"],
    )

@dataclass(frozen=True)
class Endpoints:
    native_api: str
    public_api: str

def bind_endpoints(values: Mapping[str, str]) -> Endpoints:
    if "native-api" not in values:
        raise BindError("endpoint", "native-api")
    if "public-api" not in values:
        raise BindError("endpoint", "public-api")
    return Endpoints(
        native_api=values["native-api"],
        public_api=values["public-api"],
    )

def bind_integrations(values: Mapping[str, Mapping[str, str]]) -> Integrations:
    return Integrations()
