// @generated by stackless bind. DO NOT EDIT.
// fingerprint: sha256:10a25dc67e384236e9bc6c864ad2fdf4ea0ff7e98afc266fc4d9f9f7293a1b54

export const IDL_FINGERPRINT = "sha256:10a25dc67e384236e9bc6c864ad2fdf4ea0ff7e98afc266fc4d9f9f7293a1b54" as const;
export const STACK_NAME = "endpoint-test" as const;
export const SERVICE_DNS = ["web"] as const;
export type ServiceDns = (typeof SERVICE_DNS)[number];

export const INTEGRATION_DNS = [] as const;
export type IntegrationDns = (typeof INTEGRATION_DNS)[number];

export const SECRETS_REQUIRED = [] as const;

export type Integrations = {
};

export type Origins = {
  web: string;
};

export class BindError extends Error {
  constructor(
    readonly reason: "endpoint" | "service" | "integration" | "output",
    readonly dns: string,
    readonly outputKey?: string,
  ) {
    const message =
      reason === "endpoint" ? `missing URL for endpoint ${dns}` :
      reason === "service"
        ? `missing origin for service ${dns}`
        : reason === "integration"
          ? `missing integration ${dns}`
          : `missing output ${outputKey} for integration ${dns}`;
    super(message);
    this.name = "BindError";
  }
}

export function bindOrigins(map: Record<string, string>): Origins {
  const web = map["web"];
  if (web === undefined) throw new BindError("service", "web");
  return {
    web: web,
  };
}

export type Endpoints = {
  nativeApi: string;
  publicApi: string;
};

export function bindEndpoints(map: Record<string, string>): Endpoints {
  const nativeApi = map["native-api"];
  if (nativeApi === undefined) throw new BindError("endpoint", "native-api");
  const publicApi = map["public-api"];
  if (publicApi === undefined) throw new BindError("endpoint", "public-api");
  return {
    nativeApi: nativeApi,
    publicApi: publicApi,
  };
}

export function bindIntegrations(map: Record<string, Record<string, string>>): Integrations {
  return {
  };
}
