// @generated by stackless bind. DO NOT EDIT.
// fingerprint: sha256:10a25dc67e384236e9bc6c864ad2fdf4ea0ff7e98afc266fc4d9f9f7293a1b54

#[allow(dead_code, clippy::enum_variant_names)]
#[rustfmt::skip]
mod __stackless_bind {
use std::collections::BTreeMap;

pub const IDL_FINGERPRINT: &str = "sha256:10a25dc67e384236e9bc6c864ad2fdf4ea0ff7e98afc266fc4d9f9f7293a1b54";
pub const STACK_NAME: &str = "endpoint-test";
pub const ROOT_ORIGIN_SERVICE: Option<&str> = None;
pub const SERVICE_DNS: &[&str] = &[
    "web",
];
pub const INTEGRATION_DNS: &[&str] = &[
];
pub const SECRETS_REQUIRED: &[&str] = &[
];

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Integrations {
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Origins {
    pub web: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BindError {
    MissingEndpoint { dns: &'static str },
    MissingService { dns: &'static str },
    MissingIntegration { dns: &'static str },
    MissingOutput { integration: &'static str, key: &'static str },
}

impl std::fmt::Display for BindError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::MissingEndpoint { dns } => write!(f, "missing URL for endpoint {dns}"),
            Self::MissingService { dns } => write!(f, "missing origin for service {dns}"),
            Self::MissingIntegration { dns } => write!(f, "missing integration {dns}"),
            Self::MissingOutput { integration, key } => write!(f, "missing output {key} for integration {integration}"),
        }
    }
}

impl std::error::Error for BindError {}

impl Origins {
    pub fn from_map(map: &BTreeMap<String, String>) -> Result<Self, BindError> {
        Ok(Self {
            web: map
                .get("web")
                .cloned()
                .ok_or(BindError::MissingService { dns: "web" })?,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Endpoints {
    pub native_api: String,
    pub public_api: String,
}

impl Endpoints {
    pub fn from_map(map: &BTreeMap<String, String>) -> Result<Self, BindError> {
        Ok(Self {
            native_api: map.get("native-api").cloned().ok_or(BindError::MissingEndpoint { dns: "native-api" })?,
            public_api: map.get("public-api").cloned().ok_or(BindError::MissingEndpoint { dns: "public-api" })?,
        })
    }
}

impl Integrations {
    pub fn from_map(_map: &BTreeMap<String, BTreeMap<String, String>>) -> Result<Self, BindError> {
        Ok(Self {
        })
    }
}

}
pub use __stackless_bind::*;
