// Code generated by stackless bind. DO NOT EDIT.
// fingerprint: sha256:10a25dc67e384236e9bc6c864ad2fdf4ea0ff7e98afc266fc4d9f9f7293a1b54

package stacklessbind

const IDLFingerprint = "sha256:10a25dc67e384236e9bc6c864ad2fdf4ea0ff7e98afc266fc4d9f9f7293a1b54"
const StackName = "endpoint-test"

var SecretsRequired = []string{}

type ServiceDNS string

const (
	ServiceDNSWeb ServiceDNS = "web"
)

type IntegrationDNS string

type Integrations struct {
}

type Origins struct {
	Web string `json:"web"`
}

type BindErrorKind int

const (
	BindErrorMissingService BindErrorKind = iota
	BindErrorMissingIntegration
	BindErrorMissingOutput
	BindErrorMissingEndpoint
)

type BindError struct {
	Kind BindErrorKind
	DNS string
	OutputKey string
}

func (e *BindError) Error() string {
	switch e.Kind {
	case BindErrorMissingEndpoint:
		return "missing URL for endpoint " + e.DNS
	case BindErrorMissingService:
		return "missing origin for service " + e.DNS
	case BindErrorMissingIntegration:
		return "missing integration " + e.DNS
	default:
		return "missing output " + e.OutputKey + " for integration " + e.DNS
	}
}

func BindOrigins(values map[string]string) (Origins, error) {
	var out Origins
	vWeb, ok := values["web"]
	if !ok {
		return Origins{}, &BindError{Kind: BindErrorMissingService, DNS: "web"}
	}
	out.Web = vWeb
	return out, nil
}

type Endpoints struct {
	NativeApi string `json:"native-api"`
	PublicApi string `json:"public-api"`
}

func BindEndpoints(values map[string]string) (Endpoints, error) {
	var out Endpoints
	vNativeApi, ok := values["native-api"]
	if !ok { return Endpoints{}, &BindError{Kind: BindErrorMissingEndpoint, DNS: "native-api"} }
	out.NativeApi = vNativeApi
	vPublicApi, ok := values["public-api"]
	if !ok { return Endpoints{}, &BindError{Kind: BindErrorMissingEndpoint, DNS: "public-api"} }
	out.PublicApi = vPublicApi
	return out, nil
}

func BindIntegrations(values map[string]map[string]string) (Integrations, error) {
	var out Integrations
	return out, nil
}
