// @generated by stackless bind. DO NOT EDIT.
// fingerprint: sha256:1228a24dc92b50568bb3d56fc8007b4ec7dd14d6e64d65f0a04973dbac5d5568

#[allow(dead_code)]
#[cfg_attr(rustfmt, rustfmt::skip)]
mod __stackless_bind {
use std::collections::BTreeMap;

pub const IDL_FINGERPRINT: &str = "sha256:1228a24dc92b50568bb3d56fc8007b4ec7dd14d6e64d65f0a04973dbac5d5568";
pub const STACK_NAME: &str = "hello";
pub const ROOT_ORIGIN_SERVICE: Option<&str> = Some("web");
pub const SERVICE_DNS: &[&str] = &[
    "web",
];
pub const SECRETS_REQUIRED: &[&str] = &[
];

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Origins {
    pub web: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BindError {
    MissingService { dns: &'static str },
}

impl std::fmt::Display for BindError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::MissingService { dns } => write!(f, "missing origin for service {dns}"),
        }
    }
}

impl std::error::Error for BindError {}

impl Origins {
    pub fn from_map(map: &BTreeMap<String, String>) -> Result<Self, BindError> {
        Ok(Self {
            web: map
                .get("web")
                .cloned()
                .ok_or(BindError::MissingService { dns: "web" })?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum VerifyTier {
    Default,
    Smoke,
}

impl VerifyTier {
    pub const fn as_wire(self) -> Option<&'static str> {
        match self {
            Self::Default => None,
            Self::Smoke => Some("smoke"),
        }
    }
}
}
pub use __stackless_bind::*;
