// @generated by stackless bind. DO NOT EDIT.
// fingerprint: sha256:1228a24dc92b50568bb3d56fc8007b4ec7dd14d6e64d65f0a04973dbac5d5568

export const IDL_FINGERPRINT = "sha256:1228a24dc92b50568bb3d56fc8007b4ec7dd14d6e64d65f0a04973dbac5d5568" as const;
export const STACK_NAME = "hello" as const;
export const SERVICE_DNS = ["web"] as const;
export type ServiceDns = (typeof SERVICE_DNS)[number];

export type Origins = {
  web: string;
};

export class BindError extends Error {
  constructor(readonly dns: ServiceDns) {
    super(`missing origin for service ${dns}`);
    this.name = "BindError";
  }
}

export function bindOrigins(map: Record<string, string>): Origins {
  const web = map["web"];
  if (web === undefined) throw new BindError("web");
  return {
    web: web,
  };
}

export const VerifyTier = {
  default: "default",
  smoke: "smoke",
} as const;
export type VerifyTier = (typeof VerifyTier)[keyof typeof VerifyTier];
