// Code generated by stackless bind. DO NOT EDIT.
// fingerprint: sha256:1228a24dc92b50568bb3d56fc8007b4ec7dd14d6e64d65f0a04973dbac5d5568

package stacklessbind

const IDLFingerprint = "sha256:1228a24dc92b50568bb3d56fc8007b4ec7dd14d6e64d65f0a04973dbac5d5568"
const StackName = "hello"

type ServiceDNS string

const (
	ServiceDNSWeb ServiceDNS = "web"
)

type Origins struct {
	Web string `json:"web"`
}

type BindError struct {
	DNS ServiceDNS
}

func (e *BindError) Error() string {
	return "missing origin for service " + string(e.DNS)
}

func BindOrigins(values map[string]string) (Origins, error) {
	var out Origins
	vWeb, ok := values["web"]
	if !ok {
		return Origins{}, &BindError{DNS: ServiceDNSWeb}
	}
	out.Web = vWeb
	return out, nil
}

type VerifyTier string

const (
	VerifyTierDefault VerifyTier = ""
	VerifyTierSmoke VerifyTier = "smoke"
)

func (t VerifyTier) Wire() (string, bool) {
	if t == "" {
		return "", false
	}
	return string(t), true
}
