# @generated by stackless bind. DO NOT EDIT.
# fingerprint: sha256:1228a24dc92b50568bb3d56fc8007b4ec7dd14d6e64d65f0a04973dbac5d5568

from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping

IDL_FINGERPRINT = "sha256:1228a24dc92b50568bb3d56fc8007b4ec7dd14d6e64d65f0a04973dbac5d5568"
STACK_NAME = "hello"
SERVICE_DNS = ("web",)

class BindError(Exception):
    def __init__(self, dns: str) -> None:
        self.dns = dns
        super().__init__(f"missing origin for service {dns}")

@dataclass(frozen=True)
class Origins:
    web: str

def bind_origins(values: Mapping[str, str]) -> Origins:
    if "web" not in values:
        raise BindError("web")
    return Origins(
        web=values["web"],
    )

class VerifyTier:
    DEFAULT = "default"
    SMOKE = "smoke"
