//! The Vercel REST client: post-provisioning steps Stripe Projects cannot
//! express — environment variables, git deployments, deploy polling, and
//! teardown verification.
//!
//! This is a thin adapter over the [`vercel_client`] crate, generated by
//! progenitor from Vercel's OpenAPI spec (`specs/vercel-openapi.json`, trimmed
//! to the endpoints we use). The adapter maps the generated typed calls to our
//! [`VercelError`]/`Fault` model and domain types.

use std::time::Duration;

use vercel_client::types;

use crate::config::ServiceVercel;
use crate::error::VercelError;
use crate::git::GitHubRepo;

const DEFAULT_BASE: &str = "https://api.vercel.com";

/// Deploy budget: Vercel builds can run longer than local dev servers.
pub const DEPLOY_BUDGET: Duration = Duration::from_secs(35 * 60);
/// The public-origin health wait budget (§7).
pub const HEALTH_BUDGET: Duration = Duration::from_secs(5 * 60);

const POLL_INTERVAL: Duration = Duration::from_secs(10);
const REQUEST_TIMEOUT: Duration = Duration::from_secs(60);

#[derive(Debug, Clone)]
pub struct VercelProject {
    pub id: String,
    pub name: String,
}

#[derive(Debug, Clone)]
pub struct VercelDeployment {
    pub id: String,
    pub url: String,
    pub status: String,
}

/// One file in a file-upload deployment: its path relative to the deploy root,
/// and the raw bytes (base64-encoded inline at the API boundary).
#[derive(Debug, Clone)]
pub struct UploadFile {
    pub path: String,
    pub data: Vec<u8>,
}

pub struct VercelApi {
    client: vercel_client::Client,
    /// The same authed reqwest client the generated client wraps, kept for the
    /// one call (`create_git_deployment`) that needs a query param the generated
    /// client doesn't expose and an error body it doesn't surface.
    http: reqwest::Client,
    base: String,
    team_id: Option<String>,
    poll_interval: Duration,
}

impl std::fmt::Debug for VercelApi {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("VercelApi")
            .field("team_id", &self.team_id)
            .finish_non_exhaustive()
    }
}

fn authed_client(token: &str) -> reqwest::Client {
    let mut headers = reqwest::header::HeaderMap::new();
    if let Ok(mut value) = reqwest::header::HeaderValue::from_str(&format!("Bearer {token}")) {
        value.set_sensitive(true);
        headers.insert(reqwest::header::AUTHORIZATION, value);
    }
    reqwest::Client::builder()
        .default_headers(headers)
        .timeout(REQUEST_TIMEOUT)
        .build()
        .unwrap_or_else(|_| reqwest::Client::new())
}

fn api_failed(method: &str, path: &str, err: impl std::fmt::Display) -> VercelError {
    VercelError::ApiFailed {
        method: method.to_owned(),
        path: path.to_owned(),
        detail: err.to_string(),
    }
}

impl VercelApi {
    pub fn new(token: impl Into<String>, team_id: Option<String>) -> Self {
        Self::with_base(token, team_id, DEFAULT_BASE)
    }

    pub fn with_base(
        token: impl Into<String>,
        team_id: Option<String>,
        base: impl Into<String>,
    ) -> Self {
        let base = base.into();
        let http = authed_client(&token.into());
        let client = vercel_client::Client::new_with_client(&base, http.clone());
        Self {
            client,
            http,
            base,
            team_id,
            poll_interval: POLL_INTERVAL,
        }
    }

    pub fn with_poll_interval(mut self, interval: Duration) -> Self {
        self.poll_interval = interval;
        self
    }

    fn team(&self) -> Option<&str> {
        self.team_id.as_deref()
    }

    /// Append `teamId` to `url`, picking `&` or `?` by whether `url` already
    /// carries a query string — so callers never hand-choose the separator.
    fn append_team(&self, url: &mut String) {
        if let Some(team) = self.team() {
            let sep = if url.contains('?') { '&' } else { '?' };
            url.push(sep);
            url.push_str("teamId=");
            url.push_str(team);
        }
    }

    /// `/v13/deployments` with the `skipAutoDetectionConfirmation` flag (required
    /// to deploy a brand-new project without an interactive framework-detection
    /// prompt) and `teamId` when configured.
    fn deployments_url(&self) -> String {
        let mut url = format!(
            "{}/v13/deployments?skipAutoDetectionConfirmation=1",
            self.base
        );
        self.append_team(&mut url);
        url
    }

    /// `/v9/projects/{id}` with `teamId` when configured.
    fn project_url(&self, project_id: &str) -> String {
        let mut url = format!("{}/v9/projects/{project_id}", self.base);
        self.append_team(&mut url);
        url
    }

    pub async fn find_project_by_name(
        &self,
        name: &str,
    ) -> Result<Option<VercelProject>, VercelError> {
        let search = types::GetProjectsSearch::try_from(name)
            .map_err(|err| api_failed("GET", "/v10/projects", err))?;
        let response = self
            .client
            .get_projects(Some(&search), None, self.team())
            .await
            .map_err(|err| api_failed("GET", "/v10/projects", err))?
            .into_inner();
        for project in response.projects {
            if project.name.as_deref() == Some(name)
                && let Some(id) = project.id
            {
                return Ok(Some(VercelProject {
                    id,
                    name: name.to_owned(),
                }));
            }
        }
        Ok(None)
    }

    pub async fn get_project(
        &self,
        project_id: &str,
    ) -> Result<Option<VercelProject>, VercelError> {
        let id_or_name = types::GetProjectIdOrName::String(project_id.to_owned());
        match self
            .client
            .get_project(&id_or_name, None, self.team())
            .await
        {
            Ok(response) => {
                let project = response.into_inner();
                Ok(Some(VercelProject {
                    id: project.id.unwrap_or_else(|| project_id.to_owned()),
                    name: project.name.unwrap_or_else(|| project_id.to_owned()),
                }))
            }
            Err(err) if err.status().map(|s| s.as_u16()) == Some(404) => Ok(None),
            Err(err) => Err(api_failed("GET", "/v9/projects/{id}", err)),
        }
    }

    pub async fn delete_project(&self, project_id: &str) -> Result<(), VercelError> {
        self.client
            .delete_project(project_id, None, self.team())
            .await
            .map_err(|err| api_failed("DELETE", "/v9/projects/{id}", err))?;
        Ok(())
    }

    pub async fn put_env_vars(
        &self,
        project_id: &str,
        vars: &[(String, String)],
    ) -> Result<(), VercelError> {
        for (key, value) in vars {
            let body = types::CreateProjectEnvBody {
                key: Some(key.clone()),
                value: Some(value.clone()),
                type_: Some("encrypted".to_owned()),
                target: vec![
                    "production".to_owned(),
                    "preview".to_owned(),
                    "development".to_owned(),
                ],
            };
            self.client
                .create_project_env(project_id, None, self.team(), None, &body)
                .await
                .map_err(|err| api_failed("POST", "/v10/projects/{id}/env", err))?;
        }
        Ok(())
    }

    pub async fn create_git_deployment(
        &self,
        project_id: &str,
        name: &str,
        github: &GitHubRepo,
        git_ref: &str,
        cfg: &ServiceVercel,
    ) -> Result<VercelDeployment, VercelError> {
        // Posted raw via `post_deployment`: the generated client exposes neither
        // the `skipAutoDetectionConfirmation` query param nor the error body.
        //
        // Only include settings the caller actually set — Vercel's schema is
        // string-only, so sending explicit nulls for unset fields can be rejected
        // or misread. Absent settings + the skip-confirmation flag let Vercel
        // auto-detect.
        let mut settings = serde_json::Map::new();
        for (key, value) in [
            ("framework", cfg.framework.as_deref()),
            ("buildCommand", cfg.build.as_deref()),
            ("installCommand", cfg.install.as_deref()),
            ("rootDirectory", cfg.root.as_deref()),
            ("outputDirectory", cfg.output.as_deref()),
        ] {
            if let Some(value) = value {
                settings.insert(key.to_owned(), serde_json::Value::String(value.to_owned()));
            }
        }
        let mut body = serde_json::json!({
            "name": name,
            "project": project_id,
            "gitSource": {
                "type": "github",
                "org": github.org.as_str(),
                "repo": github.repo.as_str(),
                "ref": git_ref,
            },
        });
        if !settings.is_empty() {
            body["projectSettings"] = serde_json::Value::Object(settings);
        }
        self.post_deployment(&body).await
    }

    /// POST a deployment body to `/v13/deployments` (raw — the generated client
    /// can't pass `skipAutoDetectionConfirmation` and hides error bodies) and
    /// parse the response. Shared by git and file deployments.
    async fn post_deployment(
        &self,
        body: &serde_json::Value,
    ) -> Result<VercelDeployment, VercelError> {
        let url = self.deployments_url();
        let response = self
            .http
            .post(&url)
            .json(body)
            .send()
            .await
            .map_err(|err| api_failed("POST", "/v13/deployments", err))?;
        let status = response.status();
        let text = response.text().await.unwrap_or_default();
        if !status.is_success() {
            return Err(VercelError::ApiFailed {
                method: "POST".to_owned(),
                path: "/v13/deployments".to_owned(),
                detail: format!("{status}: {}", text.trim()),
            });
        }
        let value: serde_json::Value = serde_json::from_str(&text)
            .map_err(|err| api_failed("POST", "/v13/deployments", err))?;
        let id = value["id"].as_str().unwrap_or_default().to_owned();
        if id.is_empty() {
            return Err(VercelError::ApiFailed {
                method: "POST".to_owned(),
                path: "/v13/deployments".to_owned(),
                detail: format!("deployment response had no id: {}", text.trim()),
            });
        }
        Ok(VercelDeployment {
            id,
            url: value["url"].as_str().unwrap_or_default().to_owned(),
            status: value["status"]
                .as_str()
                .or_else(|| value["readyState"].as_str())
                .unwrap_or("QUEUED")
                .to_owned(),
        })
    }

    /// Create a deployment by uploading files inline (base64) — no git source,
    /// so it needs no Vercel↔GitHub connection. Suited to static/prebuilt output;
    /// very large trees would want the sha-based upload protocol.
    pub async fn create_file_deployment(
        &self,
        project_id: &str,
        name: &str,
        files: &[UploadFile],
    ) -> Result<VercelDeployment, VercelError> {
        use base64::Engine as _;
        let entries: Vec<serde_json::Value> = files
            .iter()
            .map(|file| {
                serde_json::json!({
                    "file": file.path,
                    "data": base64::engine::general_purpose::STANDARD.encode(&file.data),
                    "encoding": "base64",
                })
            })
            .collect();
        let body = serde_json::json!({
            "name": name,
            "project": project_id,
            "target": "production",
            "files": entries,
        });
        self.post_deployment(&body).await
    }

    /// Make the project's deployments publicly reachable so the health gate can
    /// hit them: stackless owns disposable stacks, so it clears Vercel's SSO /
    /// deployment protection on the projects it provisions.
    pub async fn disable_deployment_protection(&self, project_id: &str) -> Result<(), VercelError> {
        let url = self.project_url(project_id);
        let response = self
            .http
            .patch(&url)
            .json(&serde_json::json!({ "ssoProtection": null }))
            .send()
            .await
            .map_err(|err| api_failed("PATCH", "/v9/projects/{id}", err))?;
        let status = response.status();
        if !status.is_success() {
            let text = response.text().await.unwrap_or_default();
            return Err(VercelError::ApiFailed {
                method: "PATCH".to_owned(),
                path: "/v9/projects/{id}".to_owned(),
                detail: format!("{status}: {}", text.trim()),
            });
        }
        Ok(())
    }

    pub async fn get_deployment(
        &self,
        deployment_id: &str,
    ) -> Result<VercelDeployment, VercelError> {
        let deploy = self
            .client
            .get_deployment(deployment_id, None, self.team())
            .await
            .map_err(|err| api_failed("GET", "/v13/deployments/{id}", err))?
            .into_inner();
        Ok(VercelDeployment {
            id: deploy.id.unwrap_or_else(|| deployment_id.to_owned()),
            url: deploy.url.unwrap_or_default(),
            status: deploy
                .status
                .or(deploy.ready_state)
                .unwrap_or_else(|| "UNKNOWN".to_owned()),
        })
    }

    /// Recent deployment build events for the `logs` verb (§2 — a bounded
    /// window, no streaming). Hand-written: the trimmed OpenAPI client omits
    /// `/v3/deployments/{id}/events`.
    pub async fn deployment_build_events(
        &self,
        deployment_id: &str,
        tail: usize,
    ) -> Result<Vec<String>, VercelError> {
        let mut url = format!(
            "{}/v3/deployments/{deployment_id}/events?direction=backward&limit={}",
            self.base,
            tail.max(1)
        );
        self.append_team(&mut url);
        let response = self
            .http
            .get(&url)
            .send()
            .await
            .map_err(|err| api_failed("GET", "/v3/deployments/{id}/events", err))?;
        let status = response.status();
        let text = response.text().await.unwrap_or_default();
        if !status.is_success() {
            return Err(VercelError::ApiFailed {
                method: "GET".to_owned(),
                path: "/v3/deployments/{id}/events".to_owned(),
                detail: format!("{status}: {}", text.trim()),
            });
        }
        let events: Vec<serde_json::Value> = if text.trim().is_empty() {
            Vec::new()
        } else {
            serde_json::from_str(&text)
                .map_err(|err| api_failed("GET", "/v3/deployments/{id}/events", err))?
        };
        Ok(format_deployment_events(events))
    }

    pub async fn wait_for_deployment(
        &self,
        service: &str,
        deployment_id: &str,
        budget: Duration,
    ) -> Result<VercelDeployment, VercelError> {
        let deadline = tokio::time::Instant::now() + budget;
        loop {
            let deploy = self.get_deployment(deployment_id).await?;
            match deploy.status.as_str() {
                "READY" => return Ok(deploy),
                "ERROR" | "CANCELED" => {
                    return Err(VercelError::DeployFailed {
                        service: service.to_owned(),
                        status: deploy.status,
                    });
                }
                _ => {}
            }
            if tokio::time::Instant::now() >= deadline {
                return Err(VercelError::DeployTimeout {
                    service: service.to_owned(),
                    budget_secs: budget.as_secs(),
                });
            }
            tokio::time::sleep(self.poll_interval).await;
        }
    }
}

fn format_deployment_events(events: Vec<serde_json::Value>) -> Vec<String> {
    let mut lines = Vec::with_capacity(events.len());
    for event in events {
        let event_type = event
            .get("type")
            .and_then(serde_json::Value::as_str)
            .unwrap_or("event");
        let created = event
            .get("created")
            .and_then(serde_json::Value::as_f64)
            .map(|ts| format!("{ts:.0}"))
            .unwrap_or_default();
        let payload = event.get("payload").unwrap_or(&event);
        let text = payload
            .get("text")
            .and_then(serde_json::Value::as_str)
            .filter(|line| !line.is_empty())
            .map(str::to_owned)
            .or_else(|| {
                payload
                    .get("info")
                    .and_then(|info| {
                        let name = info.get("name").and_then(serde_json::Value::as_str)?;
                        let step = info
                            .get("step")
                            .and_then(serde_json::Value::as_str)
                            .unwrap_or("");
                        let state = info
                            .get("readyState")
                            .and_then(serde_json::Value::as_str)
                            .unwrap_or("");
                        let line = format!("{name} {step} {state}").trim().to_owned();
                        (!line.is_empty()).then_some(line)
                    })
                    .filter(|line| !line.is_empty())
            })
            .unwrap_or_default();
        if text.is_empty() {
            lines.push(format!("{created} [{event_type}]"));
        } else {
            lines.push(format!("{created} [{event_type}] {text}"));
        }
    }
    lines.reverse();
    lines
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::git::GitHubRepo;
    use wiremock::matchers::{body_partial_json, method, path, path_regex, query_param};
    use wiremock::{Mock, MockServer, ResponseTemplate};

    #[tokio::test]
    async fn find_project_by_name_hit() {
        let server = MockServer::start().await;
        Mock::given(method("GET"))
            .and(path_regex(r"/v10/projects.*"))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({
                "projects": [{ "id": "prj_1", "name": "atto-demo-api" }]
            })))
            .mount(&server)
            .await;
        let api = VercelApi::with_base("tok_test", None, server.uri());
        let found = api.find_project_by_name("atto-demo-api").await.unwrap();
        assert_eq!(found.as_ref().map(|p| p.id.as_str()), Some("prj_1"));
    }

    #[tokio::test]
    async fn wait_for_deployment_reaches_ready() {
        let server = MockServer::start().await;
        Mock::given(method("GET"))
            .and(path_regex(r"/v13/deployments/dpl_1.*"))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({
                "id": "dpl_1",
                "url": "atto-demo-api.vercel.app",
                "status": "READY"
            })))
            .mount(&server)
            .await;
        let api = VercelApi::with_base("tok_test", None, server.uri())
            .with_poll_interval(Duration::from_millis(1));
        let deploy = api
            .wait_for_deployment("api", "dpl_1", Duration::from_secs(1))
            .await
            .unwrap();
        assert_eq!(deploy.url, "atto-demo-api.vercel.app");
    }

    #[tokio::test]
    async fn git_deployment_sends_skip_confirmation_and_settings() {
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .and(path("/v13/deployments"))
            .and(query_param("skipAutoDetectionConfirmation", "1"))
            .and(body_partial_json(serde_json::json!({
                "project": "prj_1",
                "gitSource": { "type": "github", "org": "acme", "repo": "web", "ref": "main" },
                "projectSettings": { "rootDirectory": "site" },
            })))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({
                "id": "dpl_1", "url": "x.vercel.app", "readyState": "QUEUED"
            })))
            .mount(&server)
            .await;
        let api = VercelApi::with_base("tok", None, server.uri());
        let cfg = ServiceVercel {
            root: Some("site".into()),
            ..Default::default()
        };
        let github = GitHubRepo {
            org: "acme".into(),
            repo: "web".into(),
        };
        let deploy = api
            .create_git_deployment("prj_1", "web", &github, "main", &cfg)
            .await
            .unwrap();
        assert_eq!(deploy.id, "dpl_1");
    }

    #[tokio::test]
    async fn file_deployment_uploads_inline_without_git_source() {
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .and(path("/v13/deployments"))
            .and(query_param("skipAutoDetectionConfirmation", "1"))
            // file deploys carry `target` + `files` and no `gitSource`.
            .and(body_partial_json(serde_json::json!({
                "project": "prj_1",
                "target": "production",
                "files": [{ "file": "index.html", "encoding": "base64" }],
            })))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({
                "id": "dpl_2", "url": "y.vercel.app", "status": "READY"
            })))
            .mount(&server)
            .await;
        let api = VercelApi::with_base("tok", None, server.uri());
        let files = vec![UploadFile {
            path: "index.html".to_owned(),
            data: b"<p>hi</p>".to_vec(),
        }];
        let deploy = api
            .create_file_deployment("prj_1", "web", &files)
            .await
            .unwrap();
        assert_eq!(deploy.id, "dpl_2");
    }

    #[tokio::test]
    async fn deployment_build_events_formats_log_lines() {
        let server = MockServer::start().await;
        Mock::given(method("GET"))
            .and(path_regex(r"/v3/deployments/dpl_1/events.*"))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!([
                {
                    "type": "stdout",
                    "created": 1_540_095_775_941.0,
                    "payload": { "text": "Build completed" }
                },
                {
                    "type": "deployment-state",
                    "created": 1_540_095_776_000.0,
                    "payload": {
                        "info": { "name": "Build", "step": "complete", "readyState": "READY" }
                    }
                }
            ])))
            .mount(&server)
            .await;
        let api = VercelApi::with_base("tok", None, server.uri());
        let lines = api.deployment_build_events("dpl_1", 10).await.unwrap();
        assert_eq!(lines.len(), 2);
        assert!(lines.iter().any(|line| line.contains("Build completed")));
        assert!(lines.iter().any(|line| line.contains("READY")));
    }

    #[tokio::test]
    async fn disable_protection_clears_sso() {
        let server = MockServer::start().await;
        Mock::given(method("PATCH"))
            .and(path("/v9/projects/prj_1"))
            .and(body_partial_json(
                serde_json::json!({ "ssoProtection": serde_json::Value::Null }),
            ))
            .respond_with(
                ResponseTemplate::new(200).set_body_json(serde_json::json!({ "id": "prj_1" })),
            )
            .mount(&server)
            .await;
        let api = VercelApi::with_base("tok", None, server.uri());
        api.disable_deployment_protection("prj_1").await.unwrap();
    }
}
