//! The Vercel REST client: post-provisioning steps Stripe Projects cannot
//! express — environment variables, git deployments, deploy polling, and
//! teardown verification.
//!
//! This is a thin adapter over the [`vercel_client`] crate, generated by
//! progenitor from Vercel's OpenAPI spec (`specs/vercel-openapi.json`, trimmed
//! to the endpoints we use). The adapter maps the generated typed calls to our
//! [`VercelError`]/`Fault` model and domain types.

use std::time::Duration;

use vercel_client::types;

use crate::config::ServiceVercel;
use crate::error::VercelError;
use crate::git::GitHubRepo;

const DEFAULT_BASE: &str = "https://api.vercel.com";

/// Deploy budget: Vercel builds can run longer than local dev servers.
pub const DEPLOY_BUDGET: Duration = Duration::from_secs(35 * 60);
/// The public-origin health wait budget (§7).
pub const HEALTH_BUDGET: Duration = Duration::from_secs(5 * 60);

const POLL_INTERVAL: Duration = Duration::from_secs(10);
const REQUEST_TIMEOUT: Duration = Duration::from_secs(60);

#[derive(Debug, Clone)]
pub struct VercelProject {
    pub id: String,
    pub name: String,
}

#[derive(Debug, Clone)]
pub struct VercelDeployment {
    pub id: String,
    pub url: String,
    pub status: String,
}

pub struct VercelApi {
    client: vercel_client::Client,
    team_id: Option<String>,
    poll_interval: Duration,
}

impl std::fmt::Debug for VercelApi {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("VercelApi")
            .field("team_id", &self.team_id)
            .finish_non_exhaustive()
    }
}

fn authed_client(token: &str) -> reqwest::Client {
    let mut headers = reqwest::header::HeaderMap::new();
    if let Ok(mut value) = reqwest::header::HeaderValue::from_str(&format!("Bearer {token}")) {
        value.set_sensitive(true);
        headers.insert(reqwest::header::AUTHORIZATION, value);
    }
    reqwest::Client::builder()
        .default_headers(headers)
        .timeout(REQUEST_TIMEOUT)
        .build()
        .unwrap_or_else(|_| reqwest::Client::new())
}

fn api_failed(method: &str, path: &str, err: impl std::fmt::Display) -> VercelError {
    VercelError::ApiFailed {
        method: method.to_owned(),
        path: path.to_owned(),
        detail: err.to_string(),
    }
}

impl VercelApi {
    pub fn new(token: impl Into<String>, team_id: Option<String>) -> Self {
        Self::with_base(token, team_id, DEFAULT_BASE)
    }

    pub fn with_base(
        token: impl Into<String>,
        team_id: Option<String>,
        base: impl Into<String>,
    ) -> Self {
        let client =
            vercel_client::Client::new_with_client(&base.into(), authed_client(&token.into()));
        Self {
            client,
            team_id,
            poll_interval: POLL_INTERVAL,
        }
    }

    pub fn with_poll_interval(mut self, interval: Duration) -> Self {
        self.poll_interval = interval;
        self
    }

    fn team(&self) -> Option<&str> {
        self.team_id.as_deref()
    }

    pub async fn find_project_by_name(
        &self,
        name: &str,
    ) -> Result<Option<VercelProject>, VercelError> {
        let search = types::GetProjectsSearch::try_from(name)
            .map_err(|err| api_failed("GET", "/v10/projects", err))?;
        let response = self
            .client
            .get_projects(Some(&search), None, self.team())
            .await
            .map_err(|err| api_failed("GET", "/v10/projects", err))?
            .into_inner();
        for project in response.projects {
            if project.name.as_deref() == Some(name)
                && let Some(id) = project.id
            {
                return Ok(Some(VercelProject {
                    id,
                    name: name.to_owned(),
                }));
            }
        }
        Ok(None)
    }

    pub async fn get_project(
        &self,
        project_id: &str,
    ) -> Result<Option<VercelProject>, VercelError> {
        let id_or_name = types::GetProjectIdOrName::String(project_id.to_owned());
        match self
            .client
            .get_project(&id_or_name, None, self.team())
            .await
        {
            Ok(response) => {
                let project = response.into_inner();
                Ok(Some(VercelProject {
                    id: project.id.unwrap_or_else(|| project_id.to_owned()),
                    name: project.name.unwrap_or_else(|| project_id.to_owned()),
                }))
            }
            Err(err) if err.status().map(|s| s.as_u16()) == Some(404) => Ok(None),
            Err(err) => Err(api_failed("GET", "/v9/projects/{id}", err)),
        }
    }

    pub async fn delete_project(&self, project_id: &str) -> Result<(), VercelError> {
        self.client
            .delete_project(project_id, None, self.team())
            .await
            .map_err(|err| api_failed("DELETE", "/v9/projects/{id}", err))?;
        Ok(())
    }

    pub async fn put_env_vars(
        &self,
        project_id: &str,
        vars: &[(String, String)],
    ) -> Result<(), VercelError> {
        for (key, value) in vars {
            let body = types::CreateProjectEnvBody {
                key: Some(key.clone()),
                value: Some(value.clone()),
                type_: Some("encrypted".to_owned()),
                target: vec![
                    "production".to_owned(),
                    "preview".to_owned(),
                    "development".to_owned(),
                ],
            };
            self.client
                .create_project_env(project_id, None, self.team(), None, &body)
                .await
                .map_err(|err| api_failed("POST", "/v10/projects/{id}/env", err))?;
        }
        Ok(())
    }

    pub async fn create_git_deployment(
        &self,
        project_id: &str,
        name: &str,
        github: &GitHubRepo,
        git_ref: &str,
        cfg: &ServiceVercel,
    ) -> Result<VercelDeployment, VercelError> {
        let project_settings = (cfg.framework.is_some()
            || cfg.build.is_some()
            || cfg.install.is_some()
            || cfg.root.is_some()
            || cfg.output.is_some())
        .then(|| types::CreateDeploymentBodyProjectSettings {
            framework: cfg.framework.clone(),
            build_command: cfg.build.clone(),
            install_command: cfg.install.clone(),
            root_directory: cfg.root.clone(),
            output_directory: cfg.output.clone(),
        });
        let body = types::CreateDeploymentBody {
            name: Some(name.to_owned()),
            project: Some(project_id.to_owned()),
            git_source: Some(types::CreateDeploymentBodyGitSource {
                type_: Some("github".to_owned()),
                org: Some(github.org.clone()),
                repo: Some(github.repo.clone()),
                ref_: Some(git_ref.to_owned()),
            }),
            project_settings,
        };
        let deploy = self
            .client
            .create_deployment(None, self.team(), &body)
            .await
            .map_err(|err| api_failed("POST", "/v13/deployments", err))?
            .into_inner();
        Ok(VercelDeployment {
            id: deploy.id.unwrap_or_default(),
            url: deploy.url.unwrap_or_default(),
            status: deploy
                .status
                .or(deploy.ready_state)
                .unwrap_or_else(|| "QUEUED".to_owned()),
        })
    }

    pub async fn get_deployment(
        &self,
        deployment_id: &str,
    ) -> Result<VercelDeployment, VercelError> {
        let deploy = self
            .client
            .get_deployment(deployment_id, None, self.team())
            .await
            .map_err(|err| api_failed("GET", "/v13/deployments/{id}", err))?
            .into_inner();
        Ok(VercelDeployment {
            id: deploy.id.unwrap_or_else(|| deployment_id.to_owned()),
            url: deploy.url.unwrap_or_default(),
            status: deploy
                .status
                .or(deploy.ready_state)
                .unwrap_or_else(|| "UNKNOWN".to_owned()),
        })
    }

    pub async fn wait_for_deployment(
        &self,
        service: &str,
        deployment_id: &str,
        budget: Duration,
    ) -> Result<VercelDeployment, VercelError> {
        let deadline = tokio::time::Instant::now() + budget;
        loop {
            let deploy = self.get_deployment(deployment_id).await?;
            match deploy.status.as_str() {
                "READY" => return Ok(deploy),
                "ERROR" | "CANCELED" => {
                    return Err(VercelError::DeployFailed {
                        service: service.to_owned(),
                        status: deploy.status,
                    });
                }
                _ => {}
            }
            if tokio::time::Instant::now() >= deadline {
                return Err(VercelError::DeployTimeout {
                    service: service.to_owned(),
                    budget_secs: budget.as_secs(),
                });
            }
            tokio::time::sleep(self.poll_interval).await;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use wiremock::matchers::{method, path_regex};
    use wiremock::{Mock, MockServer, ResponseTemplate};

    #[tokio::test]
    async fn find_project_by_name_hit() {
        let server = MockServer::start().await;
        Mock::given(method("GET"))
            .and(path_regex(r"/v10/projects.*"))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({
                "projects": [{ "id": "prj_1", "name": "atto-demo-api" }]
            })))
            .mount(&server)
            .await;
        let api = VercelApi::with_base("tok_test", None, &server.uri());
        let found = api.find_project_by_name("atto-demo-api").await.unwrap();
        assert_eq!(found.as_ref().map(|p| p.id.as_str()), Some("prj_1"));
    }

    #[tokio::test]
    async fn wait_for_deployment_reaches_ready() {
        let server = MockServer::start().await;
        Mock::given(method("GET"))
            .and(path_regex(r"/v13/deployments/dpl_1.*"))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({
                "id": "dpl_1",
                "url": "atto-demo-api.vercel.app",
                "status": "READY"
            })))
            .mount(&server)
            .await;
        let api = VercelApi::with_base("tok_test", None, &server.uri())
            .with_poll_interval(Duration::from_millis(1));
        let deploy = api
            .wait_for_deployment("api", "dpl_1", Duration::from_secs(1))
            .await
            .unwrap();
        assert_eq!(deploy.url, "atto-demo-api.vercel.app");
    }
}
