// @generated by stackless bind. DO NOT EDIT.
// fingerprint: sha256:447809cf4198d6d067e1c09b494b9d29cee10edc8734ec30d55df21cffa4f412

export const IDL_FINGERPRINT = "sha256:447809cf4198d6d067e1c09b494b9d29cee10edc8734ec30d55df21cffa4f412" as const;
export const STACK_NAME = "hello" as const;
export const SERVICE_DNS = ["web"] as const;
export type ServiceDns = (typeof SERVICE_DNS)[number];

export type Origins = {
  web: string;
};

export class BindError extends Error {
  constructor(readonly dns: ServiceDns) {
    super(`missing origin for service ${dns}`);
    this.name = "BindError";
  }
}

export function bindOrigins(map: Record<string, string>): Origins {
  const web = map["web"];
  if (web === undefined) throw new BindError("web");
  return {
    web: web,
  };
}

export const VerifyTier = {
  default: "default",
  smoke: "smoke",
} as const;
export type VerifyTier = (typeof VerifyTier)[keyof typeof VerifyTier];
