//! Pure Go printer over a deserialized IDL.

use crate::emit_common::escape_str;
use crate::error::IdlError;
use crate::model::InterfaceV1;
use crate::naming::IdentNamespace;
use crate::naming::go::{GoNames, check_collisions, is_keyword_package};
use crate::naming::named_entries;

struct IntegrationEmit {
    dns: String,
    names: GoNames,
    outputs: Vec<(String, GoNames)>,
}

pub fn emit_go(idl: &InterfaceV1, package: &str) -> Result<String, IdlError> {
    validate_package(package)?;

    let service_names = named_entries(
        idl.body.services.iter().map(|s| s.dns.as_str()),
        IdentNamespace::Service,
        GoNames::from_dns,
        check_collisions,
    )?;
    let tier_names = named_entries(
        idl.body.verify.tiers.iter().map(|t| t.dns.as_str()),
        IdentNamespace::Tier,
        GoNames::from_dns,
        check_collisions,
    )?;
    let integration_names = named_entries(
        idl.body.integrations.iter().map(|i| i.dns.as_str()),
        IdentNamespace::Integration,
        GoNames::from_dns,
        check_collisions,
    )?;
    let mut integrations = Vec::new();
    for (integration, (dns, names)) in idl.body.integrations.iter().zip(integration_names.iter()) {
        debug_assert_eq!(integration.dns, *dns);
        let outputs = named_entries(
            integration.outputs.iter().map(|k| k.as_str()),
            IdentNamespace::IntegrationOutput,
            GoNames::from_output_key,
            check_collisions,
        )?;
        integrations.push(IntegrationEmit {
            dns: integration.dns.clone(),
            names: names.clone(),
            outputs,
        });
    }

    let mut out = String::new();
    out.push_str("// Code generated by stackless bind. DO NOT EDIT.\n");
    out.push_str(&format!("// fingerprint: {}\n\n", idl.fingerprint));
    out.push_str(&format!("package {package}\n\n"));

    out.push_str(&format!(
        "const IDLFingerprint = \"{}\"\n",
        escape_str(&idl.fingerprint)
    ));
    out.push_str(&format!(
        "const StackName = \"{}\"\n\n",
        escape_str(&idl.body.source.stack_name)
    ));

    out.push_str("var SecretsRequired = []string{");
    for (i, secret) in idl.body.secrets_required.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("\"{}\"", escape_str(secret)));
    }
    out.push_str("}\n\n");

    out.push_str("type ServiceDNS string\n\n");
    out.push_str("const (\n");
    for (dns, names) in &service_names {
        out.push_str(&format!(
            "\tServiceDNS{} ServiceDNS = \"{}\"\n",
            names.const_suffix,
            escape_str(dns)
        ));
    }
    out.push_str(")\n\n");

    out.push_str("type IntegrationDNS string\n\n");
    if !idl.body.integrations.is_empty() {
        out.push_str("const (\n");
        for (dns, names) in &integration_names {
            out.push_str(&format!(
                "\tIntegrationDNS{} IntegrationDNS = \"{}\"\n",
                names.const_suffix,
                escape_str(dns)
            ));
        }
        out.push_str(")\n\n");
    }

    for integration in &integrations {
        out.push_str(&format!("type {} struct {{\n", integration.names.field));
        for (wire_key, output_names) in &integration.outputs {
            out.push_str(&format!(
                "\t{} string `json:\"{}\"`\n",
                output_names.field,
                escape_str(wire_key)
            ));
        }
        out.push_str("}\n\n");
    }

    out.push_str("type Integrations struct {\n");
    for integration in &integrations {
        out.push_str(&format!(
            "\t{} {} `json:\"{}\"`\n",
            integration.names.field,
            integration.names.field,
            escape_str(&integration.dns)
        ));
    }
    out.push_str("}\n\n");

    out.push_str("type Origins struct {\n");
    for (dns, names) in &service_names {
        out.push_str(&format!(
            "\t{} string `json:\"{}\"`\n",
            names.field,
            escape_str(dns)
        ));
    }
    out.push_str("}\n\n");

    out.push_str("type BindErrorKind int\n\n");
    out.push_str("const (\n");
    out.push_str("\tBindErrorMissingService BindErrorKind = iota\n");
    out.push_str("\tBindErrorMissingIntegration\n");
    out.push_str("\tBindErrorMissingOutput\n");
    out.push_str(")\n\n");

    out.push_str("type BindError struct {\n");
    out.push_str("\tKind BindErrorKind\n");
    out.push_str("\tDNS string\n");
    out.push_str("\tOutputKey string\n");
    out.push_str("}\n\n");
    out.push_str("func (e *BindError) Error() string {\n");
    out.push_str("\tswitch e.Kind {\n");
    out.push_str("\tcase BindErrorMissingService:\n");
    out.push_str("\t\treturn \"missing origin for service \" + e.DNS\n");
    out.push_str("\tcase BindErrorMissingIntegration:\n");
    out.push_str("\t\treturn \"missing integration \" + e.DNS\n");
    out.push_str("\tdefault:\n");
    out.push_str("\t\treturn \"missing output \" + e.OutputKey + \" for integration \" + e.DNS\n");
    out.push_str("\t}\n");
    out.push_str("}\n\n");

    out.push_str("func BindOrigins(values map[string]string) (Origins, error) {\n");
    out.push_str("\tvar out Origins\n");
    for (dns, names) in &service_names {
        out.push_str(&format!(
            "\tv{0}, ok := values[\"{1}\"]\n",
            names.field,
            escape_str(dns)
        ));
        out.push_str("\tif !ok {\n");
        out.push_str(&format!(
            "\t\treturn Origins{{}}, &BindError{{Kind: BindErrorMissingService, DNS: \"{0}\"}}\n",
            escape_str(dns)
        ));
        out.push_str("\t}\n");
        out.push_str(&format!("\tout.{} = v{}\n", names.field, names.field));
    }
    out.push_str("\treturn out, nil\n");
    out.push_str("}\n\n");

    out.push_str(
        "func BindIntegrations(values map[string]map[string]string) (Integrations, error) {\n",
    );
    out.push_str("\tvar out Integrations\n");
    for integration in &integrations {
        out.push_str(&format!(
            "\tinner, ok := values[\"{}\"]\n",
            escape_str(&integration.dns)
        ));
        out.push_str("\tif !ok {\n");
        out.push_str(&format!(
            "\t\treturn Integrations{{}}, &BindError{{Kind: BindErrorMissingIntegration, DNS: \"{}\"}}\n",
            escape_str(&integration.dns)
        ));
        out.push_str("\t}\n");
        for (wire_key, output_names) in &integration.outputs {
            out.push_str(&format!(
                "\tv{0}, ok := inner[\"{1}\"]\n",
                output_names.field,
                escape_str(wire_key)
            ));
            out.push_str("\tif !ok {\n");
            out.push_str(&format!(
                "\t\treturn Integrations{{}}, &BindError{{Kind: BindErrorMissingOutput, DNS: \"{0}\", OutputKey: \"{1}\"}}\n",
                escape_str(&integration.dns),
                escape_str(wire_key)
            ));
            out.push_str("\t}\n");
            out.push_str(&format!(
                "\tout.{}.{} = v{}\n",
                integration.names.field, output_names.field, output_names.field
            ));
        }
    }
    out.push_str("\treturn out, nil\n");
    out.push_str("}\n");

    let has_tiers = idl.body.verify.has_default || !idl.body.verify.tiers.is_empty();
    if has_tiers {
        out.push('\n');
        out.push_str("type VerifyTier string\n\n");
        out.push_str("const (\n");
        if idl.body.verify.has_default {
            out.push_str("\tVerifyTierDefault VerifyTier = \"\"\n");
        }
        for (dns, names) in &tier_names {
            out.push_str(&format!(
                "\tVerifyTier{} VerifyTier = \"{}\"\n",
                names.const_suffix,
                escape_str(dns)
            ));
        }
        out.push_str(")\n\n");
        out.push_str("func (t VerifyTier) Wire() (string, bool) {\n");
        out.push_str("\tif t == \"\" {\n");
        out.push_str("\t\treturn \"\", false\n");
        out.push_str("\t}\n");
        out.push_str("\treturn string(t), true\n");
        out.push_str("}\n");
    }

    Ok(out)
}

fn validate_package(package: &str) -> Result<(), IdlError> {
    if package.is_empty()
        || !package
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_')
        || package.chars().next().is_some_and(|c| c.is_ascii_digit())
        || is_keyword_package(package)
    {
        return Err(IdlError::InvalidGoPackage {
            name: package.to_owned(),
        });
    }
    Ok(())
}
