//! Pure Python printer over a deserialized IDL.

use crate::emit_common::escape_str;
use crate::error::IdlError;
use crate::model::InterfaceV1;
use crate::naming::IdentNamespace;
use crate::naming::named_entries;
use crate::naming::python::{PyNames, check_collisions};

pub fn emit_python(idl: &InterfaceV1) -> Result<String, IdlError> {
    let service_names = named_entries(
        idl.body.services.iter().map(|s| s.dns.as_str()),
        IdentNamespace::Service,
        PyNames::from_dns,
        check_collisions,
    )?;
    let tier_names = named_entries(
        idl.body.verify.tiers.iter().map(|t| t.dns.as_str()),
        IdentNamespace::Tier,
        PyNames::from_dns,
        check_collisions,
    )?;

    let mut out = String::new();
    out.push_str("# @generated by stackless bind. DO NOT EDIT.\n");
    out.push_str(&format!("# fingerprint: {}\n\n", idl.fingerprint));
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("from dataclasses import dataclass\n");
    out.push_str("from typing import Mapping\n\n");

    out.push_str(&format!(
        "IDL_FINGERPRINT = \"{}\"\n",
        escape_str(&idl.fingerprint)
    ));
    out.push_str(&format!(
        "STACK_NAME = \"{}\"\n",
        escape_str(&idl.body.source.stack_name)
    ));
    out.push_str("SERVICE_DNS = (");
    for (i, service) in idl.body.services.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("\"{}\"", escape_str(&service.dns)));
    }
    if idl.body.services.len() == 1 {
        out.push(',');
    }
    out.push_str(")\n\n");

    out.push_str("class BindError(Exception):\n");
    out.push_str("    def __init__(self, dns: str) -> None:\n");
    out.push_str("        self.dns = dns\n");
    out.push_str("        super().__init__(f\"missing origin for service {dns}\")\n\n");

    out.push_str("@dataclass(frozen=True)\n");
    out.push_str("class Origins:\n");
    for (_, names) in &service_names {
        out.push_str(&format!("    {}: str\n", names.field));
    }
    out.push('\n');

    out.push_str("def bind_origins(values: Mapping[str, str]) -> Origins:\n");
    for (dns, _) in &service_names {
        out.push_str(&format!("    if \"{}\" not in values:\n", escape_str(dns)));
        out.push_str(&format!(
            "        raise BindError(\"{}\")\n",
            escape_str(dns)
        ));
    }
    out.push_str("    return Origins(\n");
    for (dns, names) in &service_names {
        out.push_str(&format!(
            "        {}=values[\"{}\"],\n",
            names.field,
            escape_str(dns)
        ));
    }
    out.push_str("    )\n");

    let has_tiers = idl.body.verify.has_default || !idl.body.verify.tiers.is_empty();
    if has_tiers {
        out.push('\n');
        out.push_str("class VerifyTier:\n");
        if idl.body.verify.has_default {
            out.push_str("    DEFAULT = \"default\"\n");
        }
        for (dns, names) in &tier_names {
            out.push_str(&format!(
                "    {} = \"{}\"\n",
                names.const_name,
                escape_str(dns)
            ));
        }
    }

    Ok(out)
}
