//! Pure TypeScript printer over a deserialized IDL.

use crate::emit_common::escape_str;
use crate::error::IdlError;
use crate::model::InterfaceV1;
use crate::naming::IdentNamespace;
use crate::naming::named_entries;
use crate::naming::typescript::{TsNames, check_collisions};

struct IntegrationEmit {
    dns: String,
    names: TsNames,
    outputs: Vec<(String, TsNames)>,
}

pub fn emit_typescript(idl: &InterfaceV1) -> Result<String, IdlError> {
    let service_names = named_entries(
        idl.body.services.iter().map(|s| s.dns.as_str()),
        IdentNamespace::Service,
        TsNames::from_dns,
        check_collisions,
    )?;
    let tier_names = named_entries(
        idl.body.verify.tiers.iter().map(|t| t.dns.as_str()),
        IdentNamespace::Tier,
        TsNames::from_dns,
        check_collisions,
    )?;
    let integration_names = named_entries(
        idl.body.integrations.iter().map(|i| i.dns.as_str()),
        IdentNamespace::Integration,
        TsNames::from_dns,
        check_collisions,
    )?;
    let mut integrations = Vec::new();
    for (integration, (dns, names)) in idl.body.integrations.iter().zip(integration_names.iter()) {
        debug_assert_eq!(integration.dns, *dns);
        let outputs = named_entries(
            integration.outputs.iter().map(|k| k.as_str()),
            IdentNamespace::IntegrationOutput,
            TsNames::from_output_key,
            check_collisions,
        )?;
        integrations.push(IntegrationEmit {
            dns: integration.dns.clone(),
            names: names.clone(),
            outputs,
        });
    }

    let mut out = String::new();
    out.push_str("// @generated by stackless bind. DO NOT EDIT.\n");
    out.push_str(&format!("// fingerprint: {}\n\n", idl.fingerprint));

    out.push_str(&format!(
        "export const IDL_FINGERPRINT = \"{}\" as const;\n",
        escape_str(&idl.fingerprint)
    ));
    out.push_str(&format!(
        "export const STACK_NAME = \"{}\" as const;\n",
        escape_str(&idl.body.source.stack_name)
    ));

    out.push_str("export const SERVICE_DNS = [");
    for (i, service) in idl.body.services.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("\"{}\"", escape_str(&service.dns)));
    }
    out.push_str("] as const;\n");
    out.push_str("export type ServiceDns = (typeof SERVICE_DNS)[number];\n\n");

    out.push_str("export const INTEGRATION_DNS = [");
    for (i, integration) in idl.body.integrations.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("\"{}\"", escape_str(&integration.dns)));
    }
    out.push_str("] as const;\n");
    out.push_str("export type IntegrationDns = (typeof INTEGRATION_DNS)[number];\n\n");

    out.push_str("export const SECRETS_REQUIRED = [");
    for (i, secret) in idl.body.secrets_required.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("\"{}\"", escape_str(secret)));
    }
    out.push_str("] as const;\n\n");

    for integration in &integrations {
        out.push_str(&format!(
            "export type {} = {{\n",
            integration.names.type_name
        ));
        for (_, output_names) in &integration.outputs {
            out.push_str(&format!("  {}: string;\n", output_names.prop));
        }
        out.push_str("};\n\n");
    }

    out.push_str("export type Integrations = {\n");
    for integration in &integrations {
        out.push_str(&format!(
            "  {}: {};\n",
            integration.names.prop, integration.names.type_name
        ));
    }
    out.push_str("};\n\n");

    out.push_str("export type Origins = {\n");
    for (_, names) in &service_names {
        out.push_str(&format!("  {}: string;\n", names.prop));
    }
    out.push_str("};\n\n");

    out.push_str("export class BindError extends Error {\n");
    out.push_str("  constructor(\n");
    out.push_str("    readonly reason: \"service\" | \"integration\" | \"output\",\n");
    out.push_str("    readonly dns: string,\n");
    out.push_str("    readonly outputKey?: string,\n");
    out.push_str("  ) {\n");
    out.push_str("    const message =\n");
    out.push_str("      reason === \"service\"\n");
    out.push_str("        ? `missing origin for service ${dns}`\n");
    out.push_str("        : reason === \"integration\"\n");
    out.push_str("          ? `missing integration ${dns}`\n");
    out.push_str("          : `missing output ${outputKey} for integration ${dns}`;\n");
    out.push_str("    super(message);\n");
    out.push_str("    this.name = \"BindError\";\n");
    out.push_str("  }\n");
    out.push_str("}\n\n");

    out.push_str("export function bindOrigins(map: Record<string, string>): Origins {\n");
    for (dns, names) in &service_names {
        out.push_str(&format!(
            "  const {} = map[\"{}\"];\n",
            names.prop,
            escape_str(dns)
        ));
        out.push_str(&format!(
            "  if ({} === undefined) throw new BindError(\"service\", \"{}\");\n",
            names.prop,
            escape_str(dns)
        ));
    }
    out.push_str("  return {\n");
    for (_, names) in &service_names {
        out.push_str(&format!("    {}: {},\n", names.prop, names.prop));
    }
    out.push_str("  };\n");
    out.push_str("}\n\n");

    out.push_str(
        "export function bindIntegrations(map: Record<string, Record<string, string>>): Integrations {\n",
    );
    for integration in &integrations {
        out.push_str(&format!(
            "  const {}Outer = map[\"{}\"];\n",
            integration.names.prop,
            escape_str(&integration.dns)
        ));
        out.push_str(&format!(
            "  if ({}Outer === undefined) throw new BindError(\"integration\", \"{}\");\n",
            integration.names.prop,
            escape_str(&integration.dns)
        ));
        for (wire_key, output_names) in &integration.outputs {
            out.push_str(&format!(
                "  const {} = {}Outer[\"{}\"];\n",
                output_names.prop,
                integration.names.prop,
                escape_str(wire_key)
            ));
            out.push_str(&format!(
                "  if ({} === undefined) throw new BindError(\"output\", \"{}\", \"{}\");\n",
                output_names.prop,
                escape_str(&integration.dns),
                escape_str(wire_key)
            ));
        }
    }
    out.push_str("  return {\n");
    for integration in &integrations {
        out.push_str(&format!("    {}: {{\n", integration.names.prop));
        for (_, output_names) in &integration.outputs {
            out.push_str(&format!(
                "      {}: {},\n",
                output_names.prop, output_names.prop
            ));
        }
        out.push_str("    },\n");
    }
    out.push_str("  };\n");
    out.push_str("}\n");

    let has_tiers = idl.body.verify.has_default || !idl.body.verify.tiers.is_empty();
    if has_tiers {
        out.push('\n');
        out.push_str("export const VerifyTier = {\n");
        if idl.body.verify.has_default {
            out.push_str("  default: \"default\",\n");
        }
        for (dns, names) in &tier_names {
            out.push_str(&format!("  {}: \"{}\",\n", names.prop, escape_str(dns)));
        }
        out.push_str("} as const;\n");
        out.push_str("export type VerifyTier = (typeof VerifyTier)[keyof typeof VerifyTier];\n");
    }

    Ok(out)
}
