//! Pure TypeScript printer over a deserialized IDL.

use crate::error::IdlError;
use crate::model::InterfaceV1;

pub fn emit_typescript(idl: &InterfaceV1) -> Result<String, IdlError> {
    let mut out = String::new();
    out.push_str("// @generated by stackless bind. DO NOT EDIT.\n");
    out.push_str(&format!("// fingerprint: {}\n\n", idl.fingerprint));

    out.push_str(&format!(
        "export const IDL_FINGERPRINT = \"{}\" as const;\n",
        escape_ts_str(&idl.fingerprint)
    ));
    out.push_str(&format!(
        "export const STACK_NAME = \"{}\" as const;\n",
        escape_ts_str(&idl.source.stack_name)
    ));

    out.push_str("export const SERVICE_DNS = [");
    for (i, service) in idl.services.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("\"{}\"", escape_ts_str(&service.dns)));
    }
    out.push_str("] as const;\n");
    out.push_str("export type ServiceDns = (typeof SERVICE_DNS)[number];\n\n");

    out.push_str("export type Origins = {\n");
    for service in &idl.services {
        out.push_str(&format!("  {}: string;\n", service.idents.ts_prop));
    }
    out.push_str("};\n\n");

    out.push_str("export class BindError extends Error {\n");
    out.push_str("  constructor(readonly dns: ServiceDns) {\n");
    out.push_str("    super(`missing origin for service ${dns}`);\n");
    out.push_str("    this.name = \"BindError\";\n");
    out.push_str("  }\n");
    out.push_str("}\n\n");

    out.push_str("export function bindOrigins(map: Record<string, string>): Origins {\n");
    for service in &idl.services {
        out.push_str(&format!(
            "  const {} = map[\"{}\"];\n",
            service.idents.ts_prop,
            escape_ts_str(&service.dns)
        ));
        out.push_str(&format!(
            "  if ({} === undefined) throw new BindError(\"{}\");\n",
            service.idents.ts_prop,
            escape_ts_str(&service.dns)
        ));
    }
    out.push_str("  return {\n");
    for service in &idl.services {
        out.push_str(&format!(
            "    {}: {},\n",
            service.idents.ts_prop, service.idents.ts_prop
        ));
    }
    out.push_str("  };\n");
    out.push_str("}\n");

    let has_tiers = idl.verify.has_default || !idl.verify.tiers.is_empty();
    if has_tiers {
        out.push('\n');
        out.push_str("export const VerifyTier = {\n");
        if idl.verify.has_default {
            out.push_str("  default: \"default\",\n");
        }
        for tier in &idl.verify.tiers {
            out.push_str(&format!(
                "  {}: \"{}\",\n",
                tier.idents.ts_prop,
                escape_ts_str(&tier.dns)
            ));
        }
        out.push_str("} as const;\n");
        out.push_str("export type VerifyTier = (typeof VerifyTier)[keyof typeof VerifyTier];\n");
    }

    if !out.ends_with('\n') {
        out.push('\n');
    }
    Ok(out)
}

fn escape_ts_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
