//! Pure Rust printer over a deserialized IDL.

use crate::error::IdlError;
use crate::model::InterfaceV1;

pub fn emit_rust(idl: &InterfaceV1) -> Result<String, IdlError> {
    let mut out = String::new();
    out.push_str("// @generated by stackless bind. DO NOT EDIT.\n");
    out.push_str(&format!("// fingerprint: {}\n\n", idl.fingerprint));
    out.push_str("#![allow(dead_code)]\n");
    out.push_str("#![cfg_attr(rustfmt, rustfmt::skip)]\n\n");
    out.push_str("use std::collections::BTreeMap;\n\n");
    out.push_str(&format!(
        "pub const IDL_FINGERPRINT: &str = \"{}\";\n",
        escape_rust_str(&idl.fingerprint)
    ));
    out.push_str(&format!(
        "pub const STACK_NAME: &str = \"{}\";\n",
        escape_rust_str(&idl.source.stack_name)
    ));

    let root = idl
        .services
        .iter()
        .find(|s| s.root_origin)
        .map(|s| s.dns.as_str());
    match root {
        Some(dns) => out.push_str(&format!(
            "pub const ROOT_ORIGIN_SERVICE: Option<&str> = Some(\"{}\");\n",
            escape_rust_str(dns)
        )),
        None => out.push_str("pub const ROOT_ORIGIN_SERVICE: Option<&str> = None;\n"),
    }

    out.push_str("pub const SERVICE_DNS: &[&str] = &[\n");
    for service in &idl.services {
        out.push_str(&format!("    \"{}\",\n", escape_rust_str(&service.dns)));
    }
    out.push_str("];\n");

    out.push_str("pub const SECRETS_REQUIRED: &[&str] = &[\n");
    for secret in &idl.secrets_required {
        out.push_str(&format!("    \"{}\",\n", escape_rust_str(secret)));
    }
    out.push_str("];\n\n");

    out.push_str("#[derive(Debug, Clone, PartialEq, Eq)]\n");
    out.push_str("pub struct Origins {\n");
    for service in &idl.services {
        out.push_str(&format!("    pub {}: String,\n", service.idents.rust_field));
    }
    out.push_str("}\n\n");

    out.push_str("#[derive(Debug, Clone, PartialEq, Eq)]\n");
    out.push_str("pub enum BindError {\n");
    out.push_str("    MissingService { dns: &'static str },\n");
    out.push_str("}\n\n");

    out.push_str("impl std::fmt::Display for BindError {\n");
    out.push_str("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
    out.push_str("        match self {\n");
    out.push_str(
        "            Self::MissingService { dns } => write!(f, \"missing origin for service {dns}\"),\n",
    );
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("impl std::error::Error for BindError {}\n\n");

    out.push_str("impl Origins {\n");
    out.push_str(
        "    pub fn from_map(map: &BTreeMap<String, String>) -> Result<Self, BindError> {\n",
    );
    out.push_str("        Ok(Self {\n");
    for service in &idl.services {
        out.push_str(&format!(
            "            {}: map\n                .get(\"{}\")\n                .cloned()\n                .ok_or(BindError::MissingService {{ dns: \"{}\" }})?,\n",
            service.idents.rust_field,
            escape_rust_str(&service.dns),
            escape_rust_str(&service.dns),
        ));
    }
    out.push_str("        })\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    let has_tiers = idl.verify.has_default || !idl.verify.tiers.is_empty();
    if has_tiers {
        out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
        out.push_str("pub enum VerifyTier {\n");
        if idl.verify.has_default {
            out.push_str("    Default,\n");
        }
        for tier in &idl.verify.tiers {
            out.push_str(&format!("    {},\n", tier.idents.rust_variant));
        }
        out.push_str("}\n\n");

        out.push_str("impl VerifyTier {\n");
        out.push_str("    pub const fn as_wire(self) -> Option<&'static str> {\n");
        out.push_str("        match self {\n");
        if idl.verify.has_default {
            out.push_str("            Self::Default => None,\n");
        }
        for tier in &idl.verify.tiers {
            out.push_str(&format!(
                "            Self::{} => Some(\"{}\"),\n",
                tier.idents.rust_variant,
                escape_rust_str(&tier.dns)
            ));
        }
        out.push_str("        }\n");
        out.push_str("    }\n");
        out.push_str("}\n");
    }

    if !out.ends_with('\n') {
        out.push('\n');
    }
    Ok(out)
}

fn escape_rust_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
