//! Pure Rust printer over a deserialized IDL.

use crate::emit_common::escape_str;
use crate::error::IdlError;
use crate::model::InterfaceV1;
use crate::naming::IdentNamespace;
use crate::naming::rust::{RustNames, check_collisions};

pub fn emit_rust(idl: &InterfaceV1) -> Result<String, IdlError> {
    let service_names = named_entries(
        idl.body.services.iter().map(|s| s.dns.as_str()),
        IdentNamespace::Service,
    )?;
    let tier_names = named_entries(
        idl.body.verify.tiers.iter().map(|t| t.dns.as_str()),
        IdentNamespace::Tier,
    )?;

    let mut out = String::new();
    out.push_str("// @generated by stackless bind. DO NOT EDIT.\n");
    out.push_str(&format!("// fingerprint: {}\n\n", idl.fingerprint));
    // Module wrapper so attrs apply when the file is `include!`d (inner `#!`
    // attrs are not valid after expansion into a parent item list).
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("#[cfg_attr(rustfmt, rustfmt::skip)]\n");
    out.push_str("mod __stackless_bind {\n");
    out.push_str("use std::collections::BTreeMap;\n\n");
    out.push_str(&format!(
        "pub const IDL_FINGERPRINT: &str = \"{}\";\n",
        escape_str(&idl.fingerprint)
    ));
    out.push_str(&format!(
        "pub const STACK_NAME: &str = \"{}\";\n",
        escape_str(&idl.body.source.stack_name)
    ));

    let root = idl
        .body
        .services
        .iter()
        .find(|s| s.root_origin)
        .map(|s| s.dns.as_str());
    match root {
        Some(dns) => out.push_str(&format!(
            "pub const ROOT_ORIGIN_SERVICE: Option<&str> = Some(\"{}\");\n",
            escape_str(dns)
        )),
        None => out.push_str("pub const ROOT_ORIGIN_SERVICE: Option<&str> = None;\n"),
    }

    out.push_str("pub const SERVICE_DNS: &[&str] = &[\n");
    for service in &idl.body.services {
        out.push_str(&format!("    \"{}\",\n", escape_str(&service.dns)));
    }
    out.push_str("];\n");

    out.push_str("pub const SECRETS_REQUIRED: &[&str] = &[\n");
    for secret in &idl.body.secrets_required {
        out.push_str(&format!("    \"{}\",\n", escape_str(secret)));
    }
    out.push_str("];\n\n");

    out.push_str("#[derive(Debug, Clone, PartialEq, Eq)]\n");
    out.push_str("pub struct Origins {\n");
    for (_, names) in &service_names {
        out.push_str(&format!("    pub {}: String,\n", names.field));
    }
    out.push_str("}\n\n");

    out.push_str("#[derive(Debug, Clone, PartialEq, Eq)]\n");
    out.push_str("pub enum BindError {\n");
    out.push_str("    MissingService { dns: &'static str },\n");
    out.push_str("}\n\n");

    out.push_str("impl std::fmt::Display for BindError {\n");
    out.push_str("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
    out.push_str("        match self {\n");
    out.push_str(
        "            Self::MissingService { dns } => write!(f, \"missing origin for service {dns}\"),\n",
    );
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("impl std::error::Error for BindError {}\n\n");

    out.push_str("impl Origins {\n");
    out.push_str(
        "    pub fn from_map(map: &BTreeMap<String, String>) -> Result<Self, BindError> {\n",
    );
    out.push_str("        Ok(Self {\n");
    for (dns, names) in &service_names {
        out.push_str(&format!(
            "            {}: map\n                .get(\"{}\")\n                .cloned()\n                .ok_or(BindError::MissingService {{ dns: \"{}\" }})?,\n",
            names.field,
            escape_str(dns),
            escape_str(dns),
        ));
    }
    out.push_str("        })\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    let has_tiers = idl.body.verify.has_default || !idl.body.verify.tiers.is_empty();
    if has_tiers {
        out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
        out.push_str("pub enum VerifyTier {\n");
        if idl.body.verify.has_default {
            out.push_str("    Default,\n");
        }
        for (_, names) in &tier_names {
            out.push_str(&format!("    {},\n", names.variant));
        }
        out.push_str("}\n\n");

        out.push_str("impl VerifyTier {\n");
        out.push_str("    pub const fn as_wire(self) -> Option<&'static str> {\n");
        out.push_str("        match self {\n");
        if idl.body.verify.has_default {
            out.push_str("            Self::Default => None,\n");
        }
        for (dns, names) in &tier_names {
            out.push_str(&format!(
                "            Self::{} => Some(\"{}\"),\n",
                names.variant,
                escape_str(dns)
            ));
        }
        out.push_str("        }\n");
        out.push_str("    }\n");
        out.push_str("}\n");
    }

    out.push_str("}\n");
    out.push_str("pub use __stackless_bind::*;\n");
    Ok(out)
}

fn named_entries<'a>(
    dns_names: impl Iterator<Item = &'a str>,
    namespace: IdentNamespace,
) -> Result<Vec<(String, RustNames)>, IdlError> {
    let mut entries = Vec::new();
    for dns in dns_names {
        let names = RustNames::from_dns(dns)?;
        entries.push((dns.to_owned(), names));
    }
    check_collisions(&entries, namespace)?;
    Ok(entries)
}
