//! Pure Python printer over a deserialized IDL.

use crate::emit_common::escape_str;
use crate::error::IdlError;
use crate::model::InterfaceV1;
use crate::naming::IdentNamespace;
use crate::naming::named_entries;
use crate::naming::python::{PyNames, check_collisions};

struct IntegrationEmit {
    dns: String,
    names: PyNames,
    outputs: Vec<(String, PyNames)>,
}

pub fn emit_python(idl: &InterfaceV1) -> Result<String, IdlError> {
    let service_names = named_entries(
        idl.body.services.iter().map(|s| s.dns.as_str()),
        IdentNamespace::Service,
        PyNames::from_dns,
        check_collisions,
    )?;
    let tier_names = named_entries(
        idl.body.verify.tiers.iter().map(|t| t.dns.as_str()),
        IdentNamespace::Tier,
        PyNames::from_dns,
        check_collisions,
    )?;
    let integration_names = named_entries(
        idl.body.integrations.iter().map(|i| i.dns.as_str()),
        IdentNamespace::Integration,
        PyNames::from_dns,
        check_collisions,
    )?;
    let mut integrations = Vec::new();
    for (integration, (dns, names)) in idl.body.integrations.iter().zip(integration_names.iter()) {
        debug_assert_eq!(integration.dns, *dns);
        let outputs = named_entries(
            integration.outputs.iter().map(|k| k.as_str()),
            IdentNamespace::IntegrationOutput,
            PyNames::from_output_key,
            check_collisions,
        )?;
        integrations.push(IntegrationEmit {
            dns: integration.dns.clone(),
            names: names.clone(),
            outputs,
        });
    }

    let mut out = String::new();
    out.push_str("# @generated by stackless bind. DO NOT EDIT.\n");
    out.push_str(&format!("# fingerprint: {}\n\n", idl.fingerprint));
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("from dataclasses import dataclass\n");
    out.push_str("from typing import Literal, Mapping\n\n");

    out.push_str(&format!(
        "IDL_FINGERPRINT = \"{}\"\n",
        escape_str(&idl.fingerprint)
    ));
    out.push_str(&format!(
        "STACK_NAME = \"{}\"\n",
        escape_str(&idl.body.source.stack_name)
    ));
    out.push_str("SERVICE_DNS = (");
    for (i, service) in idl.body.services.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("\"{}\"", escape_str(&service.dns)));
    }
    if idl.body.services.len() == 1 {
        out.push(',');
    }
    out.push_str(")\n");

    out.push_str("INTEGRATION_DNS = (");
    for (i, integration) in idl.body.integrations.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("\"{}\"", escape_str(&integration.dns)));
    }
    if idl.body.integrations.len() == 1 {
        out.push(',');
    }
    out.push_str(")\n");

    out.push_str("SECRETS_REQUIRED = (");
    for (i, secret) in idl.body.secrets_required.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("\"{}\"", escape_str(secret)));
    }
    if idl.body.secrets_required.len() == 1 {
        out.push(',');
    }
    out.push_str(")\n\n");

    for integration in &integrations {
        out.push_str("@dataclass(frozen=True)\n");
        out.push_str(&format!("class {}:\n", integration.names.class_name));
        for (_, output_names) in &integration.outputs {
            out.push_str(&format!("    {}: str\n", output_names.field));
        }
        out.push('\n');
    }

    out.push_str("@dataclass(frozen=True)\n");
    out.push_str("class Integrations:\n");
    if integrations.is_empty() {
        out.push_str("    pass\n");
    } else {
        for integration in &integrations {
            out.push_str(&format!(
                "    {}: {}\n",
                integration.names.field, integration.names.class_name
            ));
        }
    }
    out.push('\n');

    out.push_str("class BindError(Exception):\n");
    out.push_str("    def __init__(\n");
    out.push_str("        self,\n");
    out.push_str("        reason: Literal[\"service\", \"integration\", \"output\"],\n");
    out.push_str("        dns: str,\n");
    out.push_str("        output_key: str | None = None,\n");
    out.push_str("    ) -> None:\n");
    out.push_str("        self.reason = reason\n");
    out.push_str("        self.dns = dns\n");
    out.push_str("        self.output_key = output_key\n");
    out.push_str("        if reason == \"service\":\n");
    out.push_str("            message = f\"missing origin for service {dns}\"\n");
    out.push_str("        elif reason == \"integration\":\n");
    out.push_str("            message = f\"missing integration {dns}\"\n");
    out.push_str("        else:\n");
    out.push_str("            message = f\"missing output {output_key} for integration {dns}\"\n");
    out.push_str("        super().__init__(message)\n\n");

    out.push_str("@dataclass(frozen=True)\n");
    out.push_str("class Origins:\n");
    for (_, names) in &service_names {
        out.push_str(&format!("    {}: str\n", names.field));
    }
    out.push('\n');

    out.push_str("def bind_origins(values: Mapping[str, str]) -> Origins:\n");
    for (dns, _) in &service_names {
        out.push_str(&format!("    if \"{}\" not in values:\n", escape_str(dns)));
        out.push_str(&format!(
            "        raise BindError(\"service\", \"{}\")\n",
            escape_str(dns)
        ));
    }
    out.push_str("    return Origins(\n");
    for (dns, names) in &service_names {
        out.push_str(&format!(
            "        {}=values[\"{}\"],\n",
            names.field,
            escape_str(dns)
        ));
    }
    out.push_str("    )\n\n");

    out.push_str(
        "def bind_integrations(values: Mapping[str, Mapping[str, str]]) -> Integrations:\n",
    );
    if integrations.is_empty() {
        out.push_str("    return Integrations()\n");
    } else {
        for integration in &integrations {
            out.push_str(&format!(
                "    if \"{}\" not in values:\n",
                escape_str(&integration.dns)
            ));
            out.push_str(&format!(
                "        raise BindError(\"integration\", \"{}\")\n",
                escape_str(&integration.dns)
            ));
            out.push_str(&format!(
                "    {}_inner = values[\"{}\"]\n",
                integration.names.field,
                escape_str(&integration.dns)
            ));
            for (wire_key, _output_names) in &integration.outputs {
                out.push_str(&format!(
                    "    if \"{}\" not in {}_inner:\n",
                    escape_str(wire_key),
                    integration.names.field
                ));
                out.push_str(&format!(
                    "        raise BindError(\"output\", \"{}\", \"{}\")\n",
                    escape_str(&integration.dns),
                    escape_str(wire_key)
                ));
            }
        }
        out.push_str("    return Integrations(\n");
        for integration in &integrations {
            out.push_str(&format!(
                "        {}={}(\n",
                integration.names.field, integration.names.class_name
            ));
            for (wire_key, output_names) in &integration.outputs {
                out.push_str(&format!(
                    "            {}={}_inner[\"{}\"],\n",
                    output_names.field,
                    integration.names.field,
                    escape_str(wire_key)
                ));
            }
            out.push_str("        ),\n");
        }
        out.push_str("    )\n");
    }

    let has_tiers = idl.body.verify.has_default || !idl.body.verify.tiers.is_empty();
    if has_tiers {
        out.push('\n');
        out.push_str("class VerifyTier:\n");
        if idl.body.verify.has_default {
            out.push_str("    DEFAULT = \"default\"\n");
        }
        for (dns, names) in &tier_names {
            out.push_str(&format!(
                "    {} = \"{}\"\n",
                names.const_name,
                escape_str(dns)
            ));
        }
    }

    Ok(out)
}
